{% set name = "fpathlib" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fpathlib-{{ version }}.tar.gz
  sha256: 8ff44332a465c2adb5c45f94d6ee79c958fb50c39e896b16734d0d8208026c77

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools >=68
    - setuptools_scm
    - wheel
  run:
    - python >=3.12
    - parse

test:
  imports:
    - fpathlib

about:
  summary: A package to combine paths with metadata
  license: MIT
  home: https://github.com/LockhartLab/fpathlib

extra:
  recipe-maintainers:
    - clockhart
