{% set name = "fpathlib" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fpathlib-{{ version }}.tar.gz
  sha256: 083299d5a41577484af5a8447d185a6ab1c190b2dfe31690375349c163ea61ab

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools >=68
    - setuptools_scm
    - wheel
  run:
    - python >=3.12
    - parse

test:
  imports:
    - fpathlib

about:
  summary: A package to combine paths with metadata
  license: MIT
  home: https://github.com/LockhartLab/fpathlib

extra:
  recipe-maintainers:
    - clockhart
