{% set name = "fpathlib" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fpathlib-{{ version }}.tar.gz
  sha256: a7a3b1d99483a33a81db47de608a6e791a5afa155d062a5914fd9eee98878da1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools >=68
    - setuptools_scm
    - wheel
  run:
    - python >=3.12
    - parse

test:
  imports:
    - fpathlib

about:
  summary: A package to combine paths with metadata
  license: MIT
  home: https://github.com/LockhartLab/fpathlib

extra:
  recipe-maintainers:
    - clockhart
